---
name: litmus-python-ci
on:  
  push:
    branches:
      - master
    tags-ignore:
      - '**'
defaults:
  run:
    shell: bash

jobs:

  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2      
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DNAME }}
          password: ${{ secrets.DPASS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: litmuschaos/py-runner:ci